// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import BookmarkCommentController from "./bookmark_comment_controller"
application.register("bookmark-comment", BookmarkCommentController)

import BookmarkController from "./bookmark_controller"
application.register("bookmark", BookmarkController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IconController from "./icon_controller"
application.register("icon", IconController)

import MapController from "./map_controller"
application.register("map", MapController)

import RatingController from "./rating_controller"
application.register("rating", RatingController)

import ReminderController from "./reminder_controller"
application.register("reminder", ReminderController)

import SearchTaskController from "./search_task_controller"
application.register("search-task", SearchTaskController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
