// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import BookmarkCommentController from "./bookmark_comment_controller"
application.register("bookmark-comment", BookmarkCommentController)

import BookmarkController from "./bookmark_controller"
application.register("bookmark", BookmarkController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchTaskController from "./search_task_controller"
application.register("search-task", SearchTaskController)
